# Generated by Django 6.1.1 on 2026-09-22 21:18

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=64, unique=True)),
                ("user_id", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("is_fraudulent", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "transactions",
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="transaction_user_id_b5bcfd_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="transaction_timesta_07633a_idx"
                    ),
                ],
            },
        ),
    ]
